### PR TITLE
Feature: Clean up code base

### PR DESCRIPTION
**Pull request by marcobiedermann**
* Add missing training semicolon
* Add missing training comma
* Use singe quotes instead of template literals if not needed
* Use `.jsx` file extension
* Move Header component into `src/components` subfolder

This has no functional effects but takes care of some best practices and cleans up the overall code base.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey, thanks for the PR!

We use Prettier to format code — try running `npm run format`.

I dislike .jsx — it's not a "best practice" — it's simply a "practice" :-) so please revert that change.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by marcobiedermann** [comment]
@KyleAMathews Thanks for your quick reply.
Okay, I disagree but it is just a matter of taste :)
I reverted my changes.
If there is anything else I can do for you, feel free to contact me at any time :)

**Comment by KyleAMathews** [comment]
cool :-) and thanks! More issues over here :-) https://github.com/gatsbyjs/gatsby/labels/good%20first%20issue

**Pull request merged**
