### PR TITLE
prevent escaping

### PR DESCRIPTION
**Pull request by pravdomil**
see diff

### CODE REVIEW

**Comment by KyleAMathews** [comment]
👍

**Comment by jgierer12** [comment]
This change breaks the `format` script on Windows, any chance it could be reverted? Especially seeing as it was changed to double quotes to work on Windows in the first place (#35).

**Comment by KyleAMathews** [comment]
Oh, @pravdomil, what was the reason for this PR?

**Comment by pravdomil** [comment]
revert it

**Comment by KyleAMathews** [comment]
Done https://github.com/gatsbyjs/gatsby-starter-default/commit/cbaae4b4cf1900c2698031d1f858a2cad172c24e

**Pull request merged**
