### PR TITLE
Add `gatsby-image` to starter

### PR DESCRIPTION
**Pull request by lexishanson**
Solving for https://github.com/gatsbyjs/gatsby/issues/9158 to add "gatsby-image" plugin to this starter.

The `Image` component located in `src/components/image.js` uses a StaticQuery to load the image from `src/images/`. The `Image` component is added to `src/pages/index.js`. 

I went with querying for a fluid image rather than fixed. Happy to swap this out if it makes sense.

@jlengstorf recommended to grab a royalty-free image from Unsplash or something of the like. I opted to use the Gatsby Astronaut image since it fits well with the theme 🚀

screen shot 2018-10-18 at 9 42 53 pm

### CODE REVIEW

**Comment by shannonbux** [comment]
So fun! @lexishanson thanks! This is a great idea because `gatsby-image` is super awesome :)

I think once this is merged, I'll create issues to add this change to https://github.com/gatsbyjs/gatsby-starter-default

**Comment by shannonbux** [comment]
@pieh haha whoops! 😂 I meant to say, let's explain this addition in the READme file. Would you want to do that, @lexishanson? 

Like @pieh said, in the READme file we should emphasize the benefits of `gatsby-image`. (@pieh is that what you meant?)

**Comment by jlengstorf** [comment]
@pieh Do you mean something like this?

```js
/*
 * This component is built using `gatsby-image` to automatically serve optimized
 * images with lazy loading and reduced file sizes. The image is loaded using a
 * `StaticQuery`, which allows us to load the image from directly within this
 * component, rather than having to pass the image data down from pages.
 *
 * For more information, see the docs:
 * - `gatsby-image`: https://gatsby.app/gatsby-image
 * - `StaticQuery`: https://gatsby.app/staticquery
 */
```

If so, I can update the comment so we can merge this.

**Comment by pieh** [comment]
Was just about to comment I probably am bike-shedding and delaying the merge, but we can use that for sure @jlengstorf!

**Comment by lexishanson** [comment]
Thanks @pieh @shannonbux, and @jlengstorf thank you for adding the extra details in the comments - very well-said 🙂

**Pull request merged**
